### ISSUE TITLE
Bei "Element anlegen" fehlt "Abbrechen"

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#10]
![image](https://user-images.githubusercontent.com/4481320/98825920-5867db00-2435-11eb-8f5f-666fd5d87fa9.png)

**Comment by deutho** [comment]
Ein Klick außerhalb des Feldes erfüllt diesen Zweck.
Ist gängiges UI/UX Design. (ähnlich zu einem Dropdown-Feld)

**Comment by stefan-schiffer** [comment]
So schnell geht ein Close nicht  ;-) Ein Dropdown-Feld ist kein modaler Dialog. Bitte um Beispiele und Quellen für "gängig".

**Comment by deutho** [comment]
Habe ein x in der rechten oberen Ecke ergänzt.

**Comment by stefan-schiffer** [comment]
Passt.
