### ISSUE TITLE
Lazy Loading bei langsamen Internet - teilweise wird nicht auf die DB Answer gewartet

### ISSUE THREAD

**Issue by stefan-hinterhoelzl** [deutho/IT-Projekt#19]

**Comment by deutho** [comment]
Kann nicht nachproduziert werden.

Genauere Fehlerbeschreibung notwendig

**Comment by paulpuehringer** [comment]
Lazy Loading Probleme (simuliertes Slow 3G Internet) :
1. Sprachausgabe wird nur teilweise vorgelesen oder laggt extrem -> man könnte denken, dass diese gar nicht funktioniert
2. es ist möglich bereits bei der nächsten Frage zu sein und die Sprachausgabe der vorherigen Frage erst abgespielt wird
- Bildschirmaufnahme, die Problem 1 und 2 aufzeigt  https://imgur.com/Ni7I1oN

3. Antworten laden schneller als Bilder -> Bild soll mit Placeholder überdeckt werden, bis neues Bild geladen ist

**Comment by stefan-hinterhoelzl** [comment]
#3 wird in Issue 31 behandelt

**Comment by stefan-hinterhoelzl** [comment]
fixed
