### ISSUE TITLE
Diverse Symbole

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#20]
Bei der Besprechung am 02.12.2020 wurde diskutiert, ob das Symbol "Cursorpfeil" für den Auswahlmodus durch ein anderes ersetzt werden soll, zum einen, weil der Pfeil direkt auf eine Antwort zeigt und zum anderen auch deshalb, weil es bei Touch-Bedienung keinen Maus-Cursor gibt. 

Eine mögliche Alternative könnte ein Icon in der Art sein:
https://www.flaticon.com/de/kostenloses-icon/zeiger_178432
![image](https://user-images.githubusercontent.com/4481320/101000671-83d67500-355e-11eb-957e-a55105eb3dd3.png)

Wenn die Auswahl durch eine Hand symbolisiert wird, kann das Vorlesen vielleicht durch eine sprechende Person bzw. das Zuhören durch ein Ohr dargestellt sein. Das scheinen auf den ersten Blick zwar nebensächliche Kleinigkeiten zu sein, es sind aber oft gerade solche Details, die einem positiven Benutzererlebnis den letzten Schliff geben.

https://t.ly/X8jX
![image](https://user-images.githubusercontent.com/4481320/101001404-60f89080-355f-11eb-9250-1e874c8a08da.png)

**Comment by deutho** [comment]
Vielen Dank für den Input und die Grafiken.
Gefallen mir sehr und wurden soeben ausgetauscht.
