### ISSUE TITLE
Ordner und Spiele können nicht gelöscht werden

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#23]
Der Menüeintrag "Löschen" hat keine Funktion.  Für jedes Element (Ordner, Spiel, Frage etc) sollten die CRUD-Basisfunktionen verfügbar sein. CRUDO, also CRUD + order ;-) wäre noch besser, denn dann könnte man die Elemente auch individuell anordnen, aber das würde den Rahmen des Projekts wohl sprengen. Umbenennen (update) und Löschen sind jedoch essentiell. Ohne diese Funktionen geht es nicht.

**Comment by stefan-hinterhoelzl** [comment]
Löschfunktion wurde für Spiele und Ordner implementiert. 

Übergangslösung für derdiedaz Ordner + Subordner: Das Menü mit den Punkten ist zwar vorhanden, Löschen und Umbenennen funktionieren aber bei diesen Elementen nicht. Im Endeffekt soll das Menü bei diesen Ordnern ausgeblendet werden.

**Comment by paulpuehringer** [comment]
- Löschen-Button zu hell, würde mMn besser aussehen, wenn das Grün den gleichen Helligkeitsgrad, wie der Speicher-Button beim Umbenennen hat

- Löschfunktion getestet -> OK

**Comment by stefan-schiffer** [comment]
Bitte auch für die einzelnen Seiten von Spielen das Löschen vorsehen.

**Comment by stefan-hinterhoelzl** [comment]
Löschfunktion für Spiele implementiert.
Styling wird von Thomas übernommen.
