### ISSUE TITLE
Link auf Spiel führt zur Auswertung

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#27]
Dieser Link: www.derdiedaz.at/direct?user=Gerlinde-Achleitner&path=CxXIiNPxUNP1JdNG2MQ5S4KvTnR2/47e8af44-8890-4b61-a2ca-5d3f2fad64c3/qrKz91OiDsTzFmLtRJNx/43824f69-47a7-4f02-9529-c03f21c76989/QJh3YyYr4rhu4Y1xkXyC/25bd263e-6a7d-4a2c-8879-66681f147118/RBfC1IXBCD8NEZS8snYY&item={"name":"Testspiel","gameType":"vocabular-game","uid":"c1b0c180-e74c-454f-827b-cf4f5cabac96","type":"task"}

führt hierhin: 
![image](https://user-images.githubusercontent.com/4481320/101499256-5a0dbb80-396d-11eb-98d0-3d27790d9e32.png)

**Comment by deutho** [comment]
Ist dieses Spiel leer?

Also wurde es vom Lehrer angelegt und keine Frage eingefügt bevor man es als Schüler öffnet?

**Comment by stefan-schiffer** [comment]
Ja, das Spiel ist leer. Sollte genauso zu einer Fehlermeldung führen, wie wenn Link falsch ist. Wird im obigen Link ein Identifier verändert, zB "qrKz91OiDsTzFmLtRJNx" auf "ddd" zeigt derdiedaz ebenfalls die Oje-Seite.

**Comment by deutho** [comment]
Sollte behoben sein. Bei Aufruf eines leeren Spieles bekommt der Schüler eine Nachricht dass das Spiel keine Fragen enthält. Da der Lehrer welcher ein Spiel über einen geteilten Link aufruft, dieses Spiel aus der Schülersicht einsieht, sollte auch ein Lehrer diese Nachricht sehen.

**Comment by deutho** [comment]
Bei Fehlerhaftem Link wird man zur Startseite geleitet.

**Comment by deutho** [comment]
Nach verstärktem Testen, kein weiteres Fehlverhalten festgestellt.
