### ISSUE TITLE
Passwort ändern Aufforderung.

### ISSUE THREAD

**Issue by deutho** [deutho/IT-Projekt#3]
![image](https://user-images.githubusercontent.com/59829810/98674014-7ca1ba00-2358-11eb-9e33-a40a71430af2.png)

Bei manchen Benutzernamen/Passwort Kombinationen wird der Hinweis gegeben, dass aufgrund einer Datenpanne das Passwort unsicher ist.

**Comment by deutho** [comment]
Dieser Fehler wird von Google ausgelöst.
Wir können hier wenig dagegen unternehmen.

Die beste Lösung wäre es, den Nutzer zur Änderung des Passwortes aufzufordern nach dem ersten Login.

**Comment by stefan-schiffer** [comment]
Dann sollte aber das initiale Passwort sicher sein, damit die Meldung erst gar nicht angezeigt wird. Würde für den Prototyp ein sicheres (aber nicht zu komplexes) Passwort wählen, das für alle gleich ist und weiter keine Zeit ins Ändern von Passwörtern investieren. Die Sicherheitsanforderungen müssten fürs Produkt ohnehin detailliert festgelegt werden (Passwort vergessen, etc)

**Comment by stefan-hinterhoelzl** [comment]
Passwort Ändern Möglichkeit implementiert

closed
