### ISSUE TITLE
Feedback der Website bei Ladezeiten

### ISSUE THREAD

**Issue by stefan-hinterhoelzl** [deutho/IT-Projekt#31]
Website muss bei längeren Ladezeiten zwischen Fragen in einem Spiel zeigen, dass gerade geladen wird.

**Comment by stefan-schiffer** [comment]
Das Logo ist über 4 MB groß und lädt bei langsamen Internetverbindungen lange.

![image](https://user-images.githubusercontent.com/4481320/101630623-6ce2c780-3a23-11eb-8518-9db725552b42.png)

**Comment by stefan-hinterhoelzl** [comment]
Danke für den Hinweis. Wir sind uns dessen bereits bewusst und werden das Bild noch verkleinern.

**Comment by deutho** [comment]
Bild ist nun nur noch 40KB groß.

**Comment by deutho** [comment]
Es gibt nun Feedback und das Laden von Inhalten wurde optimiert. (Audiodateien laden schon während die Frage geöffnet wird, nicht erst beim Klick um das Vorlesen auszuführen.)
