### ISSUE TITLE
Lehrer soll Schülersicht sehen können.

### ISSUE THREAD

**Issue by deutho** [deutho/IT-Projekt#4]
Es ist gewünscht, dass der Lehrer aus Sicht eines Schülers die Aufgaben/Ordnerstruktur betrachten kann.

Somit soll es möglich sein, die von derdiedaz erstellten Spiele zu testen, sowie seine Eigenen durchzuspielen.

**Comment by stefan-hinterhoelzl** [comment]
Implementiert. Testen und Styling noch ausständig
