### ISSUE TITLE
Nach dem Umbenennen eines Spiels wird die Seite nicht automatisch aktualisiert

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#49]
und der Name des Spiels bleibt gleich.

**Comment by stefan-hinterhoelzl** [comment]
Fehler im meinem Nutzer nicht reproduzierbar.
Ich vermute, Sie haben versucht Ihr Spiel "Pflanzen im Sommer" umzubenennen. Bei diesem Spiel haben wichtige Felder in der Datenbank gefehlt, die beim Edit abgefragt werden. Habe diese Information manuell hinzugefügt. Sollte nun funktionieren.

**Comment by stefan-schiffer** [comment]
Issue kann geschlossen werden. Tritt nicht mehr auf.
