### ISSUE TITLE
Vorausgefüllten Text, der ersetzt werden muss, hellgrau darstellen und bei Klick ins Feld löschen

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#7]
Dzt muss der Text selbst selektiert und gelöscht werden, bevor man zu schreiben beginn.

![image](https://user-images.githubusercontent.com/4481320/98823884-e8f0ec00-2432-11eb-97b3-6874f92786c3.png)

**Comment by stefan-schiffer** [comment]
Wirklich Low Priority? Ist ziemlich lästig, und hier funktioniert es ja schon

![Unbenanntes Bild](https://user-images.githubusercontent.com/4481320/98825814-3a01df80-2435-11eb-93c1-de95577a7d62.png)

**Comment by stefan-hinterhoelzl** [comment]
done
