### ISSUE TITLE
Ordner und Spiele sollen mit URL referenzierbar sein

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#8]
Die Navigation bis zu einem bestimmten Spiel kann mühsam sein, deshalb sollen Ordner und Spiele via URL referenziert und damit auch als Browser-Lesezeichen abgelegt werden können. Zudem könnten diese Links geteilt werden, zB zwischen Lehrkräften und SuS, Lehrkräften untereinander und SuS untereinander. Geöffnet werden können soll der Links selbstverständlich nur dann, wenn man eingeloggt ist.

**Comment by deutho** [comment]
Lehrkräfte untereinander können Spiele nicht teilen.
SuS können dies, sofern sie der selben Lehrkraft untergeordnet sind.

**Comment by stefan-schiffer** [comment]
Was ich meine: Die Lehrerinnen werden ihre Spiele anderen zeigen wollen um Feedback einzuholen und das so unkompliziert wie möglich. Das ist (hoffentlich ;-) auch im Projekt ein Thema. Hier wird es dann wohl so sein müssen, dass jeder Lehrerin im Projekt jedenfalls die Schüler maxmus und student zugeordnet sind, damit sich die Lehrinnen unter diesen Kennungen einloggen und die Spiele der anderen Lehrerinnen ausprobieren können. Oder wie stellen Sie sich das sonst vor?

**Comment by stefan-hinterhoelzl** [comment]
Verspätete Antwort auf Ihre Frage: 
Implementierung jetzt: Es kann jeder Lehrer für seine Ordner/Spiele einen teilbaren Link erstellen. Dieser kann von jedem Schüler oder Lehrer benutzt werden um das Spiel zu spielen. Die Zuteilungen spielen keine Rolle. Lehrer können Spiele, die von anderen Lehrern geteilt wurden, nur spielen und nicht editieren. Wenn ein Ordner geteilt wird, inkludiert dies alle Subordner und Spiele. Weiter nach oben (vom geteilten Ordner ausgehend) kann nicht navigiert werden. 
Wir erklären das Feature der Runde am 3.12.

**Comment by stefan-hinterhoelzl** [comment]
done
