### ISSUE TITLE
Spiele sollten entsprechend verfügbaren Vorlagen ausgewählt werden können

### ISSUE THREAD

**Issue by stefan-schiffer** [deutho/IT-Projekt#9]
Beispiele: Wortschatzquiz, Verbzweitstellung, Verbklammer etc. Single Choice und Drag&Drop sind keine Spieltypen, sondern ein Auswahlverfahren und ein Interaktionsmechanismus.

![image](https://user-images.githubusercontent.com/4481320/98825407-b9db7a00-2434-11eb-9ded-e57e43e29abd.png)

**Comment by deutho** [comment]
Done
